package com.learnwithashfaq.artemis.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * OrderEntity — JPA entity mapped to the "orders" table in H2.
 *
 * ═══════════════════════════════════════════════════════════════
 * WHY A SEPARATE ENTITY FROM OrderEvent?
 * ═══════════════════════════════════════════════════════════════
 *
 * In enterprise applications, you ALWAYS keep these separate:
 *
 *   OrderRequest  → REST API input (what the user sends)
 *   OrderEvent    → JMS message payload (what travels through the queue)
 *   OrderEntity   → Database row (what gets persisted)
 *
 * They look similar but serve different purposes and evolve independently.
 * Mixing them is a common beginner mistake that leads to tight coupling.
 *
 * ═══════════════════════════════════════════════════════════════
 * JPA ANNOTATIONS EXPLAINED:
 * ═══════════════════════════════════════════════════════════════
 *
 * @Entity        → Marks this class as a JPA entity (maps to a DB table)
 * @Table(name)   → Specifies the table name. Without it, JPA uses the class name.
 * @Id            → Marks the primary key field
 * @GeneratedValue → Auto-generates the primary key (like AUTO_INCREMENT in MySQL)
 * @Column        → Customizes column properties (nullable, unique, length, etc.)
 *
 * With spring.jpa.hibernate.ddl-auto=update, Hibernate auto-creates
 * this table on startup — you don't need to write SQL!
 */
@Entity
@Table(name = "orders")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderEntity {

    /**
     * Database primary key — auto-generated by H2.
     * This is NOT the same as orderId (which is our business ID like "ORD-A1B2C3D4").
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Business order ID (e.g., "ORD-A1B2C3D4").
     * Unique constraint prevents duplicate orders in case of JMS retries.
     * This is key for IDEMPOTENCY — if a retry saves the same orderId,
     * the unique constraint catches it.
     */
    @Column(nullable = false, unique = true)
    private String orderId;

    @Column(nullable = false)
    private String productName;

    @Column(nullable = false)
    private int quantity;

    @Column(nullable = false)
    private double price;

    @Column(nullable = false)
    private double totalAmount;

    @Column(nullable = false)
    private String customerName;

    @Column(nullable = false)
    private LocalDateTime orderDate;

    /**
     * Order status tracks the processing lifecycle:
     *   PENDING    → Order received, not yet processed
     *   PROCESSING → Consumer picked it up, running 3 steps
     *   COMPLETED  → All 3 steps succeeded
     *   FAILED     → Processing failed (after all retries exhausted)
     */
    @Column(nullable = false)
    private String status;
}
