package com.learnwithashfaq.artemis.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * OrderEvent — The message that travels through the JMS queue.
 *
 * ═══════════════════════════════════════════════════════════════
 * WHY A SEPARATE DTO FROM OrderRequest?
 * ═══════════════════════════════════════════════════════════════
 *
 * In enterprise applications, the REST API DTO and the JMS message DTO
 * are usually DIFFERENT because:
 *
 * 1. The JMS message may contain ADDITIONAL fields (orderId, timestamp, status)
 *    that the user didn't provide — the system generates them.
 *
 * 2. The JMS message may EXCLUDE fields that are REST-specific
 *    (e.g., authentication tokens, request metadata).
 *
 * 3. They evolve independently — changing the REST API shouldn't break
 *    the JMS message format (and vice versa).
 *
 * ═══════════════════════════════════════════════════════════════
 * WHAT THIS LOOKS LIKE AS JSON IN THE QUEUE:
 * ═══════════════════════════════════════════════════════════════
 *
 * {
 *     "orderId": "ORD-a1b2c3d4",
 *     "productName": "iPhone 15 Pro",
 *     "quantity": 2,
 *     "price": 999.99,
 *     "totalAmount": 1999.98,
 *     "customerName": "Ashfaq",
 *     "orderDate": "2024-01-15T10:30:00",
 *     "status": "PENDING"
 * }
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderEvent {

    /** Unique order identifier, generated by the system (e.g., "ORD-a1b2c3d4"). */
    private String orderId;

    /** Product being ordered. */
    private String productName;

    /** Number of items. */
    private int quantity;

    /** Price per unit. */
    private double price;

    /** Total amount = price × quantity. Calculated by the service layer. */
    private double totalAmount;

    /** Customer who placed the order. */
    private String customerName;

    /** When the order was placed. Set by the service layer. */
    private LocalDateTime orderDate;

    /** Current status: PENDING → PROCESSING → COMPLETED / FAILED. */
    private String status;
}
